services:
  django_territorial:
    build:
      context: .
      dockerfile: django_territorial/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django_territorial.rule=Host(`django-territorial.dev.localhost`)"
      - "traefik.http.services.django_territorial.loadbalancer.server.port=8000"
    networks:
      - traefik-public

  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-public

networks:
  traefik-public:
    name: traefik-public
